package by.training.payment.command;

public enum CommandName {

	REGISTRATION, AUTHORIZATION, LOGIN, LOGOUT, RESTORE_PASSWORD, SET_LOCALE, SHOW_CURRENCIES, SHOW_USER_DATA,
	UPDATE_USER_NAME, UPDATE_USER_SURNAME, UPDATE_USER_PASSWORD, DELETE_USER_ACCOUNT, SHOW_ALL_USER_REQUESTS,
	SHOW_MENU_FOR_CREATING_REQUESTS, CREATE_REQUEST_OPEN_NEW_ACCOUNT, CREATE_REQUEST_OPEN_NEW_CARD_TO_EXISTING_ACCOUNT,
	CREATE_REQUEST_OPEN_NEW_CARD, CREATE_REQUEST_UNLOCK_CARD;

}
