package by.training.payment.command;

public enum RequestParameter {

	COMMAND, USER_LOGIN, USER_PASSWORD, USER_PASSWORD_CONFIRM, USER_EMAIL, USER_ROLE_VALUE, USER_NAME, USER_SURNAME,
	RESULT_MESSAGE, ERROR_MESSAGE, USER, CURRENT_DATE, CURRENCIES_LIST, LANGUAGE, OLD_PASSWORD, NEW_PASSWORD,
	CONFIRM_NEW_PASSWORD, USER_REQUEST_LIST;

}
