package by.training.payment.command;

public enum RequestParameter {

	COMMAND, USER_LOGIN, USER_PASSWORD, USER_PASSWORD_CONFIRM, USER_EMAIL, USER_ROLE_VALUE, USER_NAME, USER_SURNAME,
	RESULT_MESSAGE, ERROR_MESSAGE, USER, CURRENT_DATE, CURRENCIES_LIST, LANGUAGE, OLD_PASSWORD, NEW_PASSWORD, AMOUNT,
	CONFIRM_NEW_PASSWORD, USER_REQUEST, USER_REQUEST_LIST, USER_BY_LOGIN, CURRENCY, BANK_ACCOUNT_NUMBER, USER_TEXT,
	CARD_NUMBER_MASK, CARD_EXPIRATION_DATE, PAYMENT_SYSTEM, BANK_ACCOUNT_LIST, CARD_NUMBER, CVC_CODE, CARD_LIST,
	PAYMENT_PURPOSE, SENDER_CARD_NUMBER, RECEIVER_CARD_NUMBER, TRANSACTION_LIST, USER_LIST, USER_REQUEST_ID;

}
